-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE fornecedores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  cnpj TEXT,
  telefone TEXT,
  email TEXT,
  endereco TEXT,
  observacoes TEXT,
  user_id TEXT NOT NULL,
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE itens_catalogo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  descricao TEXT NOT NULL,
  categoria TEXT,
  unidade TEXT DEFAULT 'UN',
  preco_referencia REAL,
  user_id TEXT NOT NULL,
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE itens_nf (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nota_fiscal_id INTEGER NOT NULL,
  descricao TEXT NOT NULL,
  categoria TEXT,
  quantidade REAL NOT NULL,
  unidade TEXT DEFAULT 'UN',
  preco_unitario REAL NOT NULL,
  desconto REAL DEFAULT 0,
  user_id TEXT NOT NULL,
  created_at INTEGER DEFAULT (strftime('%s', 'now')),
  FOREIGN KEY (nota_fiscal_id) REFERENCES notas_fiscais(id) ON DELETE CASCADE
);

CREATE TABLE notas_fiscais (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  numero TEXT NOT NULL,
  data_emissao TEXT NOT NULL,
  data_entrada TEXT NOT NULL,
  fornecedor TEXT NOT NULL,
  cnpj TEXT,
  filial TEXT NOT NULL,
  responsavel TEXT,
  chave_acesso TEXT,
  observacoes TEXT,
  status TEXT DEFAULT 'rascunho',
  user_id TEXT NOT NULL,
  created_at INTEGER DEFAULT (strftime('%s', 'now'))
);

-- INDEXS

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX fornecedores_nome_idx ON fornecedores(nome);

CREATE INDEX fornecedores_user_id_idx ON fornecedores(user_id);

CREATE INDEX itens_catalogo_descricao_idx ON itens_catalogo(descricao);

CREATE INDEX itens_catalogo_user_id_idx ON itens_catalogo(user_id);

CREATE INDEX itens_nf_categoria_idx ON itens_nf(categoria);

CREATE INDEX itens_nf_nota_fiscal_id_idx ON itens_nf(nota_fiscal_id);

CREATE INDEX itens_nf_user_id_idx ON itens_nf(user_id);

CREATE INDEX notas_fiscais_data_idx ON notas_fiscais(data_entrada);

CREATE INDEX notas_fiscais_fornecedor_idx ON notas_fiscais(fornecedor);

CREATE INDEX notas_fiscais_user_id_idx ON notas_fiscais(user_id);
