// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, foreignKey, real } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const fornecedores = sqliteTable("fornecedores", {
	id: integer().primaryKey({ autoIncrement: true }),
	nome: text().notNull(),
	cnpj: text(),
	telefone: text(),
	email: text(),
	endereco: text(),
	observacoes: text(),
	userId: text("user_id").notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("fornecedores_nome_idx").on(table.nome),
	index("fornecedores_user_id_idx").on(table.userId),
]);

export const notasFiscais = sqliteTable("notas_fiscais", {
	id: integer().primaryKey({ autoIncrement: true }),
	numero: text().notNull(),
	dataEmissao: text("data_emissao").notNull(),
	dataEntrada: text("data_entrada").notNull(),
	fornecedor: text().notNull(),
	cnpj: text(),
	filial: text().notNull(),
	responsavel: text(),
	chaveAcesso: text("chave_acesso"),
	observacoes: text(),
	status: text().default("rascunho"),
	userId: text("user_id").notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("notas_fiscais_fornecedor_idx").on(table.fornecedor),
	index("notas_fiscais_data_idx").on(table.dataEntrada),
	index("notas_fiscais_user_id_idx").on(table.userId),
]);

export const itensNf = sqliteTable("itens_nf", {
	id: integer().primaryKey({ autoIncrement: true }),
	notaFiscalId: integer("nota_fiscal_id").notNull().references(() => notasFiscais.id, { onDelete: "cascade" } ),
	descricao: text().notNull(),
	categoria: text(),
	quantidade: real().notNull(),
	unidade: text().default("UN"),
	precoUnitario: real("preco_unitario").notNull(),
	desconto: real(),
	userId: text("user_id").notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("itens_nf_categoria_idx").on(table.categoria),
	index("itens_nf_nota_fiscal_id_idx").on(table.notaFiscalId),
	index("itens_nf_user_id_idx").on(table.userId),
]);

export const itensCatalogo = sqliteTable("itens_catalogo", {
	id: integer().primaryKey({ autoIncrement: true }),
	descricao: text().notNull(),
	categoria: text(),
	unidade: text().default("UN"),
	precoReferencia: real("preco_referencia"),
	userId: text("user_id").notNull(),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("itens_catalogo_descricao_idx").on(table.descricao),
	index("itens_catalogo_user_id_idx").on(table.userId),
]);

